class Solution {
        public int findNumberOfLIS(int[] nums) {
                int n = nums.length;
                        
                                int[] length = new int[n];   // length[i] = LIS ending at i
                                        int[] count = new int[n];    // count[i] = number of LIS ending at i
                                                
                                                        for(int i = 0; i < n; i++){
                                                                    length[i] = 1;
                                                                                count[i] = 1;
                                                                                        }
                                                                                                
                                                                                                        int maxLength = 1;
                                                                                                                
                                                                                                                        for(int i = 0; i < n; i++){
                                                                                                                                    for(int j = 0; j < i; j++){
                                                                                                                                                    
                                                                                                                                                                    if(nums[j] < nums[i]){
                                                                                                                                                                                        
                                                                                                                                                                                                            // If we found longer subsequence
                                                                                                                                                                                                                                if(length[j] + 1 > length[i]){
                                                                                                                                                                                                                                                        length[i] = length[j] + 1;
                                                                                                                                                                                                                                                                                count[i] = count[j];
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                            // If same length found again
                                                                                                                                                                                                                                                                                                                                                                else if(length[j] + 1 == length[i]){
                                                                                                                                                                                                                                                                                                                                                                                        count[i] += count[j];
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                maxLength = Math.max(maxLength, length[i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int result = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for(int i = 0; i < n; i++){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if(length[i] == maxLength){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    result += count[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
